---
id: gollem
name: Gollem
full: File manager application
description: >-
  Gollem is a web-based file manager, providing the ability to fully manage a
  hierarchical file system stored in a variety of backends such as a SQL
  database, as part of a real filesystem, or on FTP, Samba or SSH servers.
list: ~
type: application
homepage: https://www.horde.org/apps/gollem
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 5.0.0alpha2
  api: 5.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: GPL-2.0
  uri: http://www.horde.org/licenses/gpl
dependencies:
  required:
    php: ^7.4 || ^8
    composer:
      horde/horde: ^6
      horde/auth: ^3
      horde/cache: ^3
      horde/core: ^3
      horde/editor: ^3
      horde/exception: ^3
      horde/mime: ^3
      horde/mime_viewer: ^3
      horde/perms: ^3
      horde/serialize: ^3
      horde/support: ^3
      horde/url: ^3
      horde/util: ^3
      horde/vfs: ^3
      horde/view: ^3
    ext:
      gettext: '*'
      json: '*'
  optional:
    composer:
      horde/db: ^3
      horde/share: ^3
