---
id: gollem
name: Gollem
full: File manager application
description: >-
  Gollem is a web-based file manager, providing the ability to fully manage a
  hierarchical file system stored in a variety of backends such as a SQL
  database, as part of a real filesystem, or on FTP, Samba or SSH servers.
list: ~
type: application
homepage: https://www.horde.org/apps/gollem
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.14
  api: 3.0.0
state:
  release: stable
  api: stable
license:
  identifier: GPL-2.0
  uri: http://www.horde.org/licenses/gpl
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/horde: ^5.0.2
      pear.horde.org/Horde_Auth: ^2
      pear.horde.org/Horde_Cache: ^2
      pear.horde.org/Horde_Core: ^2.30
      pear.horde.org/Horde_Editor: ^2
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Mime: ^2
      pear.horde.org/Horde_Mime_Viewer: ^2
      pear.horde.org/Horde_Perms: ^2
      pear.horde.org/Horde_Serialize: ^2
      pear.horde.org/Horde_Support: ^2
      pear.horde.org/Horde_Url: ^2
      pear.horde.org/Horde_Util: ^2
      pear.horde.org/Horde_Vfs: ^2
      pear.horde.org/Horde_View: ^2
    ext:
      gettext: '*'
      json: '*'
  optional:
    pear:
      pear.horde.org/Horde_Db: ^2
      pear.horde.org/Horde_Share: ^2
