---
id: gollem
name: Gollem
full: File manager application
description: >
  Gollem is a web-based file manager, providing the ability to fully manage a
  hierarchical file system stored in a variety of backends such as a SQL
  database, as part of a real filesystem, or on FTP, Samba or SSH servers.
list:
type: application
