<?php
/**
 * AUTOGENERATED FILE WILL BE OVERWRITTEN ON EACH
 * composer horde-reconfigure or install/update
 * Override settings in either:
 * - var/config/horde/registry.local.php
 * - var/config/horde/registry.d/ snippets, i.e. 99-custom.php
 * - var/config/horde/registry-sub.domain.org.php
 */
$this->applications['horde']['fileroot'] = '/home/i567442/php/git/horde/gollem/vendor/horde/horde/';
$this->applications['horde']['templates'] = '/home/i567442/php/git/horde/gollem/vendor/horde/horde/templates/';
$this->applications['horde']['webroot'] = '/horde/';
$this->applications['horde']['jsfs'] = '/home/i567442/php/git/horde/gollem/web/js/horde/';
$this->applications['horde']['jsuri'] = '/js/horde';
$this->applications['horde']['staticfs'] = '/home/i567442/php/git/horde/gollem/web/static/';
$this->applications['horde']['staticuri'] = '/static/';
$this->applications['horde']['themesfs'] = '/home/i567442/php/git/horde/gollem/web/themes/horde/';
$this->applications['horde']['themesuri'] = '/themes/horde';
