<?php
/**
 * AUTOGENERATED FILE WILL BE OVERWRITTEN ON EACH
 * composer horde-reconfigure or install/update
 * Override settings in either:
 * - var/config/horde/registry.local.php
 * - var/config/horde/registry.d/ snippets, i.e. 99-custom.php
 * - var/config/horde/registry-sub.domain.org.php
 */
$this->applications['gollem']['fileroot'] = '/home/i567442/php/git/horde/gollem/vendor/horde/gollem/';
$this->applications['gollem']['templates'] = '/home/i567442/php/git/horde/gollem/vendor/horde/gollem/templates/';
$this->applications['gollem']['themesfs'] = '/home/i567442/php/git/horde/gollem/web/themes/gollem/';
$this->applications['gollem']['jsfs'] = '/home/i567442/php/git/horde/gollem/web/js/gollem/';
$this->applications['gollem']['webroot'] = '/gollem/';
$this->applications['gollem']['jsuri'] = '/js/gollem';
$this->applications['gollem']['themesuri'] = '/themes/gollem';
// End of gollem registry snippet
